#!/bin/sh
# @description get the agent version
# @man Displays the version of the Rudder agent and of the underlying CFEngine agent.

. "${BASEDIR}/../lib/common.sh"

VERSION_FILE="/opt/rudder/share/versions/rudder-agent-version"
if [ -e "${VERSION_FILE}" ]; then
    AGENT_VERSION=$(sed -n '/rudder_version=/s/rudder_version=//p' "${VERSION_FILE}")
elif [ -e /usr/bin/dpkg ]; then
    AGENT_VERSION=$(dpkg-query -W --showformat='${Version}' rudder-agent)
elif [ -e /usr/sbin/slackpkg ]; then
    AGENT_VERSION=$(ls -1 /var/log/packages | sed -n '/^rudder-agent-[0-9.]\+/s/^.*agent-\([0-9.]*\).*$/\1/p') 
elif [ -e /bin/rpm ]; then
    AGENT_VERSION=$(rpm -q --queryformat '%{version}' rudder-agent)
else
    AGENT_VERSION='unknown version'
fi

echo "Rudder agent ${AGENT_VERSION}"
