#!/bin/sh
# @description get the agent version
# @man Displays the version of the Rudder agent and of the underlying CFEngine agent.

. "${BASEDIR}/../lib/common.sh"

if [ -e /usr/bin/dpkg ]; then
    AGENT_VERSION=$(dpkg-query -W --showformat='${Version}' rudder-agent)
elif [ -e /bin/rpm ]; then
    AGENT_VERSION=$(rpm -q --queryformat '%{version}' rudder-agent)
else
    AGENT_VERSION='unknown version'
fi

echo "Rudder agent ${AGENT_VERSION} ($(/var/rudder/cfengine-community/bin/cf-agent -V))"
