#!/bin/sh
# @description re-initialise the agent to make it be seen as a new node on the server
# @man This command will delete all local agent data, including its uuid and
# @man keys, and also reset the agent internal state.
# @man The only configuration kept is the server hostname or ip configured in _policy_server.dat_.
# @man It will also send an inventory to the server, which will treat it as a new node inventory.
# @man +
# @man *WARNING*: This command will permanently delete your node uuid and keys, and no configuration will
# @man be applied before re-accepting and configuring the node on the server.

# - replace ppkeys
rm -f /var/rudder/cfengine-community/ppkeys/localhost*
/var/rudder/cfengine-community/bin/cf-key

# - generate a new uuid
if [ -x /opt/rudder/bin/uuidgen ]
then
  /opt/rudder/bin/uuidgen > /opt/rudder/etc/uuid.hive
else
  uuidgen > /opt/rudder/etc/uuid.hive
fi

# - remove old inventory
rm -rf /opt/rudder/var/fusioninventory/*

# - reset cfengine status
"${BASEDIR}/agent-reset"

# - resend inventory
"${BASEDIR}/agent-inventory"
