#!/bin/sh
# @description get the agent version

if [ -e /usr/bin/dpkg ]; then
    AGENT_VERSION=$(dpkg-query -W --showformat='${Version}' rudder-agent)
elif [ -e /bin/rpm ]; then
    AGENT_VERSION=$(rpm -qa --queryformat '%{version}' rudder-agent)
else
    AGENT_VERSION='unknown version'
fi

echo "Rudder agent ${AGENT_VERSION} ($(/var/rudder/cfengine-community/bin/cf-agent -V))"
