#!/bin/sh
# @description force the agent to create and send a new inventory
# @man This will trigger a new inventory creation and send it to the policy server.
# @man Even if the agent will do it regularly, it can be used to force the update
# @man after a modification on the node.
# @man This won't affect the node state, but only update server-side information.
# @man +
# @man *Options*:
# @man +
# @man *-i*: run the agent in information mode, prints basic information
# @man +
# @man *-v*: run the agent in verbose mode, prints detailed information
# @man +
# @man *-d*: run the agent in debug mode, prints low-level information
# @man +
# @man *-q*: run the agent in quiet mode (display only error messages)
# @man +
# @man *-c*: run the agent without color output

# rudder agent run -b force_inventory
VERBOSITY=""
COLOR="-C"
FILTER="cat"

while getopts "iIvdqc" opt; do
  case $opt in
    i|I)
      VERBOSITY="-I -D debug"
      ;;
    v)
      VERBOSITY="-v"
      ;;
    d)
      VERBOSITY="-d"
      ;;
    q)
      FILTER="egrep -v @@result_success@@|@@result_na@@|@@log_info@@|@@log_debug@@|\[info\]|notice:"
      ;;
    c)
      COLOR=""
      ;;
  esac
done

/var/rudder/cfengine-community/bin/cf-agent ${VERBOSITY} ${COLOR} -K -D force_inventory | ${FILTER}

