#!/bin/sh
# @description reset agent status and cache
# @man Remove all locks and state cache of the agent, and restore initial promises.
# @man This won't affect the desired state of the node, but will only
# @man reset the internal state of the agent. It is useful to test a rule
# @man without caching interference or when you have trouble with the promises updates.

# Try to remove everything that can block
# - restore initial promises
rm -rf /var/rudder/cfengine-community/inputs/*
cp -r /opt/rudder/share/initial-promises/* /var/rudder/cfengine-community/inputs

# - remove state
rm -rf /var/rudder/cfengine-community/state/*
rm -f /var/rudder/cfengine-community/*.lmdb

# - remove locks
rm -f /var/rudder/cfengine-community/*lock

# - trigger ncf and tools update on next agent run
rm -f /var/rudder/tools/rudder_tools_updated{,.tmp}
rm -f /var/rudder/ncf/{common,local}/ncf_hash_file

# - remove the disable status
rm -f /opt/rudder/etc/disable-agent
