#!/bin/sh
# @description displays or set the policy server
# @man If called without arguments, displays current policy server.
# @man Sets the epolicy server to the hostname or IP given.
# @man +
# @man *Arguments*:
# @man +
# @man *server*: hostname or IP of the policy server to set

. "${BASEDIR}/../lib/common.sh"

SERVER_FILE="${RUDDER_VAR}/cfengine-community/policy_server.dat"

CURRENT=$(cat ${SERVER_FILE} 2>/dev/null)
[ $? -ne 0 ] && CURRENT="Not yet configured"

SERVER="$1"

[ -z "$SERVER" ] && echo "${CURRENT}" && exit 0

# Let's set the policy server
[ "${UUID}" = "root" ] && printf "${RED}error${NORMAL}: Cannot change policy server on a root server\n" && exit 1

echo "${SERVER}" > "${SERVER_FILE}"
RET=$?

[ ${RET} -ne 0 ] && printf "${RED}error${NORMAL}: Could not set policy server\n"

exit ${RET}
