#!/bin/sh
# @description start the relay service
# @man Start the relay service using the appropriate service manager.
# @man +
# @man *Options*:
# @man +
# @man *-q*: run the agent in quiet mode (display only error messages)
# @man +
# @man *-c*: run the agent without color output

. "${BASEDIR}/../lib/common.sh"
. "${BASEDIR}/../lib/api_call.sh"

QUIET=false
DISPLAY_COMMAND=false

while getopts "qciIvd" opt; do
  case $opt in
    i|I|v|d)
      DISPLAY_COMMAND=true
      ;;

    q)
      QUIET=true
      ;;
    c)
      clear_colors
      ;;
  esac
done

simple_api_call "http://127.0.0.1:3030/rudder/relay-ctl/reload" "reload relayd configuration" "${DISPLAY_COMMAND}" "{\"Ok\":null}" "--request POST"

