#!/bin/bash
# @description run a debug _cf-serverd_ intended for a specific node
# @man This command targets a specific node and does not affect the running
# @man infrastructure. It uses _iptables_ to redirect the specific node communications
# @man to the port the debug server is listening on (5310 by default).
# @man +
# @man Use Ctrl+C to stop the debug server.
# @man +
# @man *Arguments*:
# @man +
# @man *node*: IP or hostname of the host you want to debug

DEBUG_PORT=5310

set -e

# necessary to manage iptables removal on error or on ctrl-c
function anomaly_handler() {
  iptables -t nat -D PREROUTING -p tcp -s ${NODE} --dport 5309 -j DNAT --to-destination :${DEBUG_PORT}
  echo ""
  echo "Debug has been stopped on step: ${STEP}"
}

trap anomaly_handler ERR INT TERM

# Parameter
STEP="INIT"
NODE="$1"
if [ -z "${NODE}" ]
then
  echo "Usage rudder server debug <node_ip>"
  exit 1
fi

STEP="Creating redirect iptables rule"
iptables -t nat -I PREROUTING -p tcp -s ${NODE} --dport 5309 -j DNAT --to-destination :${DEBUG_PORT}

STEP="Running debug server"
/var/rudder/cfengine-community/bin/cf-serverd -v --no-fork -D debug_port

STEP="Removing iptables rule"
iptables -t nat -D PREROUTING -p tcp -s ${NODE} --dport 5309 -j DNAT --to-destination :${DEBUG_PORT}
