#!/bin/bash
# @description create an admin user account
# @man This commands allows inserting a new user account. It is particularly useful
# @man to create the first admin account on the server. It requires that the
# @man authentication hash is bcrypt (default from fresh 6.1).
# @man +
# @man *Options*:
# @man +
# @man *-u*: specify the user name ("admin" by default)
# @man +
# @man *-p*: specify the user password (use with care as it is stored in history), if empty use $ADMIN_PASSWORD from the environment instead

. "${BASEDIR}/../lib/common.sh"

set -o pipefail
set -e

USERFILE="${RUDDER_DIR}/etc/rudder-users.xml"
USER="admin"
PASS_OPT=""

while getopts "u:p:" opt; do
  case $opt in
    u)
      USER="${OPTARG}"
      ;;
    p)
      PASS_OPT="b"
      if [ "${OPTARG}" != "" ]; then
        ADMIN_PASSWORD="${OPTARG}"
      fi
      ;;
  esac
done

# check hash
if ! grep -qE "^[[:space:]]*<authentication[[:space:]]+hash=\"bcrypt\".*>" "${USERFILE}"
then
  echo "This command can only create users when the 'bcrypt' hash method is used"
  echo "Particularly, for servers upgraded from pre-6.1, it requires resetting all"
  echo "user passwords when changing the hash method."
  echo "See https://docs.rudder.io/reference/6.0/administration/users.html for details."
  exit 1
fi

# check if user is already there
if grep -qE "name[[:space:]]*=[[:space:]]*\"${USER}\"" "${USERFILE}"
then
  echo "User '${USER}' already exists, aborting."
  exit 1
fi

# bcrypt (12 cost)
hash=$(htpasswd -n${PASS_OPT}BC 12 "" ${ADMIN_PASSWORD}| tr -d ':\n')

details="<user name=\"${USER}\" password=\"${hash}\" role=\"administrator\" />"
sed -i "/^[[:space:]]*<\/authentication>/i ${details}" "${USERFILE}"

echo "User '${USER}' added, restarting the Rudder server"

systemctl restart rudder-jetty >/dev/null

