#!/bin/sh
# @description Stop Rudder from distributing new policies as a server
# @man This is useful when you want to temporarily prevent your Rudder server
# @man from doing any changes on your agents

. "${BASEDIR}/../lib/common.sh"

# First, prevent the agent from restarting cf-serverd
touch /opt/rudder/etc/disable-policy-distribution

# Then disable and stop it
systemctl stop rudder-cf-serverd
systemctl disable rudder-cf-serverd

# Just in case other cf-server were running
if type killall > /dev/null 2> /dev/null; then
  killall cf-serverd 2> /den/null || true
elif type pidof > /dev/null 2> /dev/null; then
  kill $(pidof cf-serverd 2>/dev/null) 2> /dev/null || true
else
  echo "Could not check for remaining policy server processes outside of the service"
  echo "(install 'pidof' or 'killall' to enable this check)" 
fi
