#!/bin/bash
# @description reload techniques
# @man This command will reload the technique library into memory from
# @man the filesystem and regenerate the promises if necessary.
# @man +
# @man *Options*:
# @man +
# @man *-i*: run the agent in information mode, displays all executed commands
# @man +
# @man *-c*: run the agent without color output

. "${BASEDIR}/../lib/common.sh"
. "${BASEDIR}/../lib/api_call.sh"

DISPLAY_COMMAND=false

while getopts "iIvdc" opt; do
  case $opt in
    i|I|v|d)
      DISPLAY_COMMAND=true
      ;;
    c)
      clear_colors
      ;;
  esac
done

# Make call to jetty directly and bypass apache conf so we are sure we have no problem to call reload techniques API
simple_api_call "http://localhost:8080/rudder/api/techniqueLibrary/reload" "reload techniques from files" "${DISPLAY_COMMAND}" "OK" ""

