#!/bin/sh
# @description Stop Rudder from distributing new policies as a server
# @man This is useful when you want to temporarily prevent your Rudder server
# @man from doing any changes on your agents

# First, prevent the agent from restarting cf-serverd
touch /opt/rudder/etc/disable-policy-distribution

# Then, actually stop the server right now
if type killall > /dev/null 2> /dev/null; then
  killall cf-serverd
elif type pidof > /dev/null 2> /dev/null; then
  kill $(pidof cf-serverd 2>/dev/null)
else
  echo "Don't know how to stop Rudder policy server. 'killall' or 'pidof' are required." 1>&2
  echo 'Policy server not stopped!' 1>&2
  exit 2
fi
