#!/bin/sh

# Timestamps all lines
while IFS= read -r line; do
    # Same as in agent with a T instead of space (iso8601 UTC)
    date=$(date -u "+%Y-%m-%dT%T+00:00")
    printf "${date} %s\n" "$line"
done
